# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: ['push']

jobs:
  test-event-folder:

    runs-on: ubuntu-latest

    strategy:
      matrix: { dir: ['event', 'job'] }
    # defaults:
    #   run:
    #     working-directory: event
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    
    - run: ls -la
    
    - run: yarn
    
    - run: yarn test
